services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./_build:/app/_build
    stdin_open: true
    tty: true
    networks:
      default:
        aliases:
          - application

  s1:
    extends: app
    hostname: llk1
    command: elixir --sname s1 --cookie llk -S mix run --no-halt
    environment:
      - SERVICE_NAME=S1
    networks:
      - llk

  s2:
    extends: app
    hostname: llk2
    command: elixir --sname s2 --cookie llk -S mix run --no-halt
    environment:
      - SERVICE_NAME=S2
    networks:
      - llk

  s3:
    extends: app
    hostname: llk3
    command: elixir --sname s3 --cookie llk -S mix run --no-halt
    environment:
      - SERVICE_NAME=S3
    networks:
      - llk

  otel:
    image: otel/opentelemetry-collector-contrib:0.98.0
    command: ["--config=/conf/otel-collector-config.yaml"]
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./otel-collector-config.yaml:/conf/otel-collector-config.yaml
    links:
      - jaeger-all-in-one
    networks:
      - llk

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    networks:
      - llk

networks:
  default:
  llk:
    name: llk
    driver: bridge
